[package]
name = "perkpath"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.6", default-features = false, features = ["web", "macro", "signals", "hooks", "document", "html", "launch"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
geo = "0.28"
web-sys = { version = "0.3", features = ["Window", "Location"] }
gloo-timers = "0.3"
